version: "3.9"

services:
  jfr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jfr-merger
    ports:
      - "8080:8080"
    volumes:
      - app_storage:/app/storage
    restart: unless-stopped

volumes:
  app_storage:
